### ISSUE TITLE
system logs are very verbose and cannot be disabled

### ISSUE THREAD

**Issue by jackwasey** [syncthing/syncthing-macos#82] opened 2018-08-15 22:59 UTC
MacOS High Sierra, latest brew install, 90% of my Console messages are Syncthing activity. I'm guessing this is steadily chewing through my SSD, and prevents me from using the Console to review messages from every other application. I see no way of disabling this, or even reducing the extreme verbosity.

Thanks for this great tool.

**Comment by xor-gate** [comment] 2018-08-16 08:01
Thanks for reporting @jackwasey. Could you provide some lines which pollute the log? Or maybe a screenshot?

**Comment by jackwasey** [comment] 2018-08-17 09:27
<img width="768" alt="screen shot 2018-08-16 at 5 00 18 am" src="https://user-images.githubusercontent.com/7832270/44258939-288de680-a1de-11e8-9cbc-6979f422282c.png">

**Comment by cactus** [comment] 2018-09-12 23:53
Same problem....

LOTS of logging:

```
16:51:18.464703 -0700   Syncthing   Task <xxxx>.<163> sent request, body N
16:51:18.465202 -0700   Syncthing   Task <xxxx>.<163> received response, status 307 content K
16:51:18.465520 -0700   Syncthing   Task <xxxx>.<163> response ended
16:51:18.466188 -0700   Syncthing   Task <xxxx>.<163> now using Connection 5
16:51:18.466471 -0700   Syncthing   Task <xxxx>.<163> sent request, body N
16:51:18.467124 -0700   Syncthing   Task <xxxx>.<163> received response, status 200 content C
16:51:21.113830 -0700   Syncthing   Task <xxxx>.<164> now using Connection 4
16:51:21.114177 -0700   Syncthing   Task <xxxx>.<164> sent request, body N
16:51:21.114613 -0700   Syncthing   Task <xxxx>.<164> received response, status 307 content K
16:51:21.114922 -0700   Syncthing   Task <xxxx>.<164> response ended
16:51:21.115488 -0700   Syncthing   Task <xxxx>.<164> now using Connection 6
16:51:21.115758 -0700   Syncthing   Task <xxxx>.<164> sent request, body N
16:51:21.116385 -0700   Syncthing   Task <xxxx>.<164> received response, status 200 content K
16:51:21.116560 -0700   Syncthing   Task <xxxx>.<164> response ended
16:51:26.113527 -0700   Syncthing   Task <xxxx>.<165> now using Connection 4
16:51:26.113869 -0700   Syncthing   Task <xxxx>.<165> sent request, body N
16:51:26.114306 -0700   Syncthing   Task <xxxx>.<165> received response, status 307 content K
16:51:26.114593 -0700   Syncthing   Task <xxxx>.<165> response ended
16:51:26.115211 -0700   Syncthing   Task <xxxx>.<165> now using Connection 6
16:51:26.115449 -0700   Syncthing   Task <xxxx>.<165> sent request, body N
16:51:26.116078 -0700   Syncthing   Task <xxxx>.<165> received response, status 200 content K
16:51:26.116254 -0700   Syncthing   Task <xxxx>.<165> response ended
```

**Comment by xor-gate** [comment] 2018-09-19 08:48
Hi guys, I have seen this behaviour also myself. Not sure what causes it, so we need some investigation how to silence this. @calmh or @virusman do you have an idea?

**Comment by xor-gate** [comment] 2018-10-03 14:14
Hi all, i digged trough the code and google searches to figure out what actually causes this insane amount of console messages. Luckily we are not the only one as seen in this issue https://github.com/zerotier/ZeroTierOne/issues/655. Currently still no root cause found :(

**Comment by xor-gate** [comment] 2018-10-03 14:16
Here is a log at my computer from the last minute:

```
jerry@Jerrys-iMac:[~]
 > sudo log show --debug --info --style syslog --predicate 'process CONTAINS "Syncthing"' --last 1m
Filtering the log data using "process CONTAINS "Syncthing""
Timestamp                       (process)[PID]
2018-10-03 16:14:43.442442+0200  localhost Syncthing[58228]: (CFNetwork) Task <EB7543B5-1029-4AE1-AD28-78259B700945>.<2814> now using Connection 28
2018-10-03 16:14:43.442595+0200  localhost Syncthing[58228]: (CFNetwork) Task <EB7543B5-1029-4AE1-AD28-78259B700945>.<2814> sent request, body N
2018-10-03 16:14:43.442893+0200  localhost Syncthing[58228]: (CFNetwork) Task <EB7543B5-1029-4AE1-AD28-78259B700945>.<2814> received response, status 200 content K
2018-10-03 16:14:43.442979+0200  localhost Syncthing[58228]: (CFNetwork) Task <EB7543B5-1029-4AE1-AD28-78259B700945>.<2814> response ended
2018-10-03 16:14:48.442409+0200  localhost Syncthing[58228]: (CFNetwork) Task <C743AF81-DD00-45C5-9FA1-407A9D943A00>.<2815> now using Connection 28
2018-10-03 16:14:48.442580+0200  localhost Syncthing[58228]: (CFNetwork) Task <C743AF81-DD00-45C5-9FA1-407A9D943A00>.<2815> sent request, body N
2018-10-03 16:14:48.442863+0200  localhost Syncthing[58228]: (CFNetwork) Task <C743AF81-DD00-45C5-9FA1-407A9D943A00>.<2815> received response, status 200 content K
2018-10-03 16:14:48.442946+0200  localhost Syncthing[58228]: (CFNetwork) Task <C743AF81-DD00-45C5-9FA1-407A9D943A00>.<2815> response ended
2018-10-03 16:14:53.441691+0200  localhost Syncthing[58228]: (CFNetwork) Task <8DD503E2-F83F-4D83-9140-82BDDDA6D4C7>.<2816> now using Connection 28
2018-10-03 16:14:53.441878+0200  localhost Syncthing[58228]: (CFNetwork) Task <8DD503E2-F83F-4D83-9140-82BDDDA6D4C7>.<2816> sent request, body N
2018-10-03 16:14:53.442158+0200  localhost Syncthing[58228]: (CFNetwork) Task <8DD503E2-F83F-4D83-9140-82BDDDA6D4C7>.<2816> received response, status 200 content K
2018-10-03 16:14:53.442274+0200  localhost Syncthing[58228]: (CFNetwork) Task <8DD503E2-F83F-4D83-9140-82BDDDA6D4C7>.<2816> response ended
2018-10-03 16:14:58.442445+0200  localhost Syncthing[58228]: (CFNetwork) Task <DD218C55-57F1-4F24-A887-361591C4DB7D>.<2817> now using Connection 28
2018-10-03 16:14:58.442600+0200  localhost Syncthing[58228]: (CFNetwork) Task <DD218C55-57F1-4F24-A887-361591C4DB7D>.<2817> sent request, body N
2018-10-03 16:14:58.442904+0200  localhost Syncthing[58228]: (CFNetwork) Task <DD218C55-57F1-4F24-A887-361591C4DB7D>.<2817> received response, status 200 content K
2018-10-03 16:14:58.442987+0200  localhost Syncthing[58228]: (CFNetwork) Task <DD218C55-57F1-4F24-A887-361591C4DB7D>.<2817> response ended
2018-10-03 16:15:03.442355+0200  localhost Syncthing[58228]: (CFNetwork) Task <0BD52410-4D08-4800-B01C-39A5E4A9183C>.<2818> now using Connection 28
2018-10-03 16:15:03.442497+0200  localhost Syncthing[58228]: (CFNetwork) Task <0BD52410-4D08-4800-B01C-39A5E4A9183C>.<2818> sent request, body N
2018-10-03 16:15:03.442802+0200  localhost Syncthing[58228]: (CFNetwork) Task <0BD52410-4D08-4800-B01C-39A5E4A9183C>.<2818> received response, status 200 content K
2018-10-03 16:15:03.442885+0200  localhost Syncthing[58228]: (CFNetwork) Task <0BD52410-4D08-4800-B01C-39A5E4A9183C>.<2818> response ended
2018-10-03 16:15:07.252325+0200  localhost Syncthing[58228]: (CFNetwork) Task <2B82E647-D696-4EC1-A2E7-137345B789F6>.<2806> response ended
2018-10-03 16:15:07.253274+0200  localhost Syncthing[58228]: (CFNetwork) Task <2FE4B8A2-6AE9-4A61-8067-906532AC4207>.<2819> now using Connection 27
2018-10-03 16:15:07.253446+0200  localhost Syncthing[58228]: (CFNetwork) Task <2FE4B8A2-6AE9-4A61-8067-906532AC4207>.<2819> sent request, body N
2018-10-03 16:15:07.253684+0200  localhost Syncthing[58228]: (CFNetwork) Task <2FE4B8A2-6AE9-4A61-8067-906532AC4207>.<2819> received response, status 200 content C
2018-10-03 16:15:08.442470+0200  localhost Syncthing[58228]: (CFNetwork) Task <9A54972D-B00D-4F91-9FA6-4E23F4F56525>.<2820> now using Connection 28
2018-10-03 16:15:08.442636+0200  localhost Syncthing[58228]: (CFNetwork) Task <9A54972D-B00D-4F91-9FA6-4E23F4F56525>.<2820> sent request, body N
2018-10-03 16:15:08.443097+0200  localhost Syncthing[58228]: (CFNetwork) Task <9A54972D-B00D-4F91-9FA6-4E23F4F56525>.<2820> received response, status 200 content K
2018-10-03 16:15:08.443219+0200  localhost Syncthing[58228]: (CFNetwork) Task <9A54972D-B00D-4F91-9FA6-4E23F4F56525>.<2820> response ended
2018-10-03 16:15:13.442417+0200  localhost Syncthing[58228]: (CFNetwork) Task <2FB9B5E0-3E5B-4F94-8237-9F60AD85F990>.<2821> now using Connection 28
2018-10-03 16:15:13.442563+0200  localhost Syncthing[58228]: (CFNetwork) Task <2FB9B5E0-3E5B-4F94-8237-9F60AD85F990>.<2821> sent request, body N
2018-10-03 16:15:13.442905+0200  localhost Syncthing[58228]: (CFNetwork) Task <2FB9B5E0-3E5B-4F94-8237-9F60AD85F990>.<2821> received response, status 200 content K
2018-10-03 16:15:13.442993+0200  localhost Syncthing[58228]: (CFNetwork) Task <2FB9B5E0-3E5B-4F94-8237-9F60AD85F990>.<2821> response ended
2018-10-03 16:15:18.442424+0200  localhost Syncthing[58228]: (CFNetwork) Task <873F7162-43B6-4F09-8EF7-32C39017AF11>.<2822> now using Connection 28
2018-10-03 16:15:18.442574+0200  localhost Syncthing[58228]: (CFNetwork) Task <873F7162-43B6-4F09-8EF7-32C39017AF11>.<2822> sent request, body N
2018-10-03 16:15:18.442805+0200  localhost Syncthing[58228]: (CFNetwork) Task <873F7162-43B6-4F09-8EF7-32C39017AF11>.<2822> received response, status 200 content K
2018-10-03 16:15:18.442893+0200  localhost Syncthing[58228]: (CFNetwork) Task <873F7162-43B6-4F09-8EF7-32C39017AF11>.<2822> response ended
2018-10-03 16:15:23.442530+0200  localhost Syncthing[58228]: (CFNetwork) Task <392046E5-ED5D-4F53-B06E-10F20971BE86>.<2823> now using Connection 28
2018-10-03 16:15:23.442724+0200  localhost Syncthing[58228]: (CFNetwork) Task <392046E5-ED5D-4F53-B06E-10F20971BE86>.<2823> sent request, body N
2018-10-03 16:15:23.443215+0200  localhost Syncthing[58228]: (CFNetwork) Task <392046E5-ED5D-4F53-B06E-10F20971BE86>.<2823> received response, status 200 content K
2018-10-03 16:15:23.443320+0200  localhost Syncthing[58228]: (CFNetwork) Task <392046E5-ED5D-4F53-B06E-10F20971BE86>.<2823> response ended
2018-10-03 16:15:28.441426+0200  localhost Syncthing[58228]: (CFNetwork) Task <257434C6-18C1-4BD9-A995-45F8DF047F35>.<2824> now using Connection 28
2018-10-03 16:15:28.441571+0200  localhost Syncthing[58228]: (CFNetwork) Task <257434C6-18C1-4BD9-A995-45F8DF047F35>.<2824> sent request, body N
2018-10-03 16:15:28.441850+0200  localhost Syncthing[58228]: (CFNetwork) Task <257434C6-18C1-4BD9-A995-45F8DF047F35>.<2824> received response, status 200 content K
2018-10-03 16:15:28.441921+0200  localhost Syncthing[58228]: (CFNetwork) Task <257434C6-18C1-4BD9-A995-45F8DF047F35>.<2824> response ended
2018-10-03 16:15:33.441937+0200  localhost Syncthing[58228]: (CFNetwork) Task <4AA116C6-DC5E-4791-9F5C-C6475994D950>.<2825> now using Connection 28
2018-10-03 16:15:33.442266+0200  localhost Syncthing[58228]: (CFNetwork) Task <4AA116C6-DC5E-4791-9F5C-C6475994D950>.<2825> sent request, body N
2018-10-03 16:15:33.442971+0200  localhost Syncthing[58228]: (CFNetwork) Task <4AA116C6-DC5E-4791-9F5C-C6475994D950>.<2825> received response, status 200 content K
2018-10-03 16:15:33.443113+0200  localhost Syncthing[58228]: (CFNetwork) Task <4AA116C6-DC5E-4791-9F5C-C6475994D950>.<2825> response ended
2018-10-03 16:15:38.442023+0200  localhost Syncthing[58228]: (CFNetwork) Task <A08D82A2-AB66-4280-BA99-0266C30F7827>.<2826> now using Connection 28
2018-10-03 16:15:38.442166+0200  localhost Syncthing[58228]: (CFNetwork) Task <A08D82A2-AB66-4280-BA99-0266C30F7827>.<2826> sent request, body N
2018-10-03 16:15:38.442454+0200  localhost Syncthing[58228]: (CFNetwork) Task <A08D82A2-AB66-4280-BA99-0266C30F7827>.<2826> received response, status 200 content K
2018-10-03 16:15:38.442530+0200  localhost Syncthing[58228]: (CFNetwork) Task <A08D82A2-AB66-4280-BA99-0266C30F7827>.<2826> response ended
```

**Comment by calmh** [comment] 2018-10-03 14:34
You guys have CFNETWORK_DIAGNOSTICS set?

https://developer.apple.com/library/archive/qa/qa1887/_index.html

**Comment by calmh** [comment] 2018-10-03 14:36
Ah, never mind, this is apparently logged even without that. Ah well.

**Comment by xor-gate** [comment] 2018-10-03 14:37
Yes, I figure that out also.

**Comment by xor-gate** [comment] 2019-01-16 10:03
Hi Guys,

I'm closing this, because it is not only syncthing (wrapper?) which emits a lot of logging but also the system daemons etcetera. We have not figured out a way to silence it. This is a snippet from my log currently:

```
default	11:00:27.706170 +0100	Syncthing	Task <220F4410-F947-4B48-A564-DC80792EA8DF>.<42> now using Connection 4
default	11:00:27.706308 +0100	Syncthing	Task <220F4410-F947-4B48-A564-DC80792EA8DF>.<42> sent request, body N
default	11:00:27.706813 +0100	Syncthing	Task <220F4410-F947-4B48-A564-DC80792EA8DF>.<42> received response, status 200 content K
default	11:00:27.706888 +0100	Syncthing	Task <220F4410-F947-4B48-A564-DC80792EA8DF>.<42> response ended
default	11:00:27.706920 +0100	Syncthing	Task <220F4410-F947-4B48-A564-DC80792EA8DF>.<42> done using Connection 4
default	11:00:28.458768 +0100	screencapture	launched with cmd-shift-4
default	11:00:28.535007 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	11:00:28.541482 +0100	launchservicesd	CHECKIN:0x0-0x240240 22503 com.apple.screencaptureui
default	11:00:28.541633 +0100	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] | enter
default	11:00:28.542297 +0100	loginwindow	-[PersistentAppsSupport applicationLaunched:] | enter. clearing logout in progress and last logout time
default	11:00:28.542393 +0100	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : Screenshot
default	11:00:28.547180 +0100	tccd	PID[162] is checking access for target PID[22503]
default	11:00:28.550821 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	11:00:28.558803 +0100	screencaptureui	Current system appearance, (HLTB: 2), (SLS: 1)
default	11:00:28.562654 +0100	screencaptureui	Post-registration system appearance: (HLTB: 2)
```

**Closed by xor-gate** 2019-01-16 10:03 UTC
Labels: bug
